name: Music Assistant Server (Firstchair) BETA
version: 2.8.7
slug: music_assistant_youtube_beta
description: Music Assistant Server (BETA channel) with YouTube provider (yt-dlp) injected
url: https://github.com/firstchair/music-assistant-yt-dlp
arch:
  - amd64
  - aarch64
homeassistant_api: true
hassio_api: true
hassio_role: default
discovery:
  - music_assistant
auth_api: true
host_network: true
ingress: true
ingress_port: 8094
panel_icon: mdi:play-circle
panel_title: Music Assistant
panel_admin: false
uart: false
apparmor: true
map:
  - media:rw
  - ssl:ro
  - share:rw
init: false
advanced: false
backup_exclude:
  - cache.db
  - collage_images/*
  - .cache/*
stage: experimental
image: ghcr.io/firstchair/music-assistant-yt-dlp-beta/{arch}
tmpfs: true
options:
  log_level: info
  safe_mode: false
schema:
  log_level: list(debug|info|warning|error)
  safe_mode: bool
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
